# Generated by Django 5.0.7 on 2024-08-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=60)),
                ('user_type', models.CharField(choices=[('AD', 'Admin'), ('ST', 'Student'), ('IN', 'Instructor')], max_length=2)),
            ],
        ),
    ]
